### ISSUE TITLE
cc: error: unrecognized command line option '-NDEBUG'

### ISSUE THREAD

**Issue by zdtsw** [curityio/nginx_phantom_token_module#25]
checking for OS
 + Linux 4.4.0-93-generic x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 

when running "./configure" with "non-Y" for "Do you want to enable debug features (not recommended for production usage) [y/N]: "
got below error:
./configure: error: can not detect int size

from ${NGINX_SRC_DIR}/objs/autoconf.err
cc: error: unrecognized command line option '-NDEBUG'

**Comment by zdtsw** [comment]
the only thing I can think about is assert.h

**Comment by travisspencer** [comment]
This is a bug in the configure script, it seems. There, you have this on line 33:

```bash
    CONFIG_OPTS=(${CONFIG_OPTS[@]} --with-cc-opt="-NDEBUG")
```

That should be `--with-cc-opt="-DNDEBUG"`. Can you try that and see if the compiler is happier with that?

**Comment by zdtsw** [comment]
yes, work as expected
