### ISSUE TITLE
Truncated JWT when caching is disabled

### ISSUE THREAD

**Issue by travisspencer** [curityio/nginx_phantom_token_module#55]
This issue is related to issue #50. That issue fixed a problem with large JWTs when caching was enabled. When caching is not enabled though and a large JWT is returned from the introspection endpoint, the JWT is truncated. This needs to be fixed.

**Comment by gary-archer** [comment]
Fixed in [pull request 76](https://github.com/curityio/nginx_phantom_token_module/pull/76)
