### ISSUE TITLE
access token not found

### ISSUE THREAD

**Issue by mrsingh88** [curityio/nginx_phantom_token_module#66]
Hi 

we are trying to integrate phantom token with curity 7.1.0 version it seems, phantom token is clipping some of the characters of the access token. we had earlier 6.5 version of curity which had about 36 characters of access token which were well processed by phantom but now from 7.0 curity has increased it to 45 characters which is causing the issue as when it reaches introspection end point it is only 37 characters, not full 45 characters which results in introspection not getting the token and it errors 204.
Is there any size limit fixed in phantom token for access tokens.

thank you
Charandeep

**Comment by gary-archer** [comment]
Hi Charandeep - I believe you have been informed about this. There was once a bug in this area that has since been fixed:
https://github.com/curityio/nginx_phantom_token_module/issues/44

Please ensure that you are using version 1.1.0 or later of the plugin. Regards.
